package com.mycompany.dailyme;

import java.awt.Color;
import java.awt.Frame;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        myProfileButton = new javax.swing.JPanel();
        myProfileButtonText = new javax.swing.JLabel();
        myProfileButtonIcon = new javax.swing.JLabel();
        myProfileButtonBar = new javax.swing.JLabel();
        mealDiaryButton = new javax.swing.JPanel();
        mealDiaryButtonText = new javax.swing.JLabel();
        mealDiaryButtonIcon = new javax.swing.JLabel();
        mealDiaryButtonBar = new javax.swing.JLabel();
        workoutDiaryButton = new javax.swing.JPanel();
        workoutDiaryButtonText = new javax.swing.JLabel();
        workoutDiaryButtonIcon = new javax.swing.JLabel();
        workoutDiaryButtonBar = new javax.swing.JLabel();
        statsButton = new javax.swing.JPanel();
        statsButtonText = new javax.swing.JLabel();
        statsButtonIcon = new javax.swing.JLabel();
        statsButtonBar = new javax.swing.JLabel();
        calcButton = new javax.swing.JPanel();
        calcButtonText = new javax.swing.JLabel();
        calcButtonIcon = new javax.swing.JLabel();
        calcButtonBar = new javax.swing.JLabel();
        infoButton = new javax.swing.JPanel();
        infoButtonText = new javax.swing.JLabel();
        infoButtonIcon = new javax.swing.JLabel();
        infoButtonBar = new javax.swing.JLabel();
        closeButton = new javax.swing.JLabel();
        minimizeButton = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        myProfilePanel = new javax.swing.JPanel();
        myProfileBanner = new javax.swing.JLabel();
        namePanel = new javax.swing.JPanel();
        nameText = new javax.swing.JLabel();
        profileNameText = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        kcalPanel = new javax.swing.JPanel();
        todayKcalText = new javax.swing.JLabel();
        kcalValueText = new javax.swing.JLabel();
        kcalIcon = new javax.swing.JLabel();
        userParamPanel = new javax.swing.JPanel();
        bmiText = new javax.swing.JLabel();
        bmiValueText = new javax.swing.JLabel();
        noteText = new javax.swing.JLabel();
        noteValueText = new javax.swing.JLabel();
        goalText = new javax.swing.JLabel();
        goalValueText = new javax.swing.JLabel();
        goalLeftText = new javax.swing.JLabel();
        goalLeftValueText = new javax.swing.JLabel();
        maleIcon = new javax.swing.JLabel();
        weightValuePanel = new javax.swing.JPanel();
        weightText = new javax.swing.JLabel();
        weightValueText = new javax.swing.JLabel();
        heightText = new javax.swing.JLabel();
        heightValueText = new javax.swing.JLabel();
        paramChangeButton = new javax.swing.JLabel();
        cmText = new javax.swing.JLabel();
        ageText = new javax.swing.JLabel();
        ageValueText = new javax.swing.JLabel();
        kgText = new javax.swing.JLabel();
        mealDiaryPanel = new javax.swing.JPanel();
        mealDiaryBanner = new javax.swing.JLabel();
        workoutDiaryPanel = new javax.swing.JPanel();
        workoutDiaryBanner = new javax.swing.JLabel();
        statsPanel = new javax.swing.JPanel();
        statsBanner = new javax.swing.JLabel();
        calcPanel = new javax.swing.JPanel();
        calcBanner = new javax.swing.JLabel();
        infoPanel = new javax.swing.JPanel();
        infoBanner = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DailyMe");
        setBackground(new java.awt.Color(34, 40, 49));
        setIconImage(new ImageIcon(getClass().getResource("/logo_clear.png")).getImage());
        setName("frame"); // NOI18N
        setUndecorated(true);
        setResizable(false);

        mainPanel.setBackground(new java.awt.Color(34, 40, 49));
        mainPanel.setName("background"); // NOI18N
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuPanel.setBackground(new java.awt.Color(34, 40, 49));
        menuPanel.setName("rightMenu"); // NOI18N
        menuPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        myProfileButton.setBackground(new java.awt.Color(34, 40, 49));
        myProfileButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        myProfileButton.setName(""); // NOI18N
        myProfileButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                myProfileButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                myProfileButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                myProfileButtonMouseExited(evt);
            }
        });
        myProfileButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        myProfileButtonText.setBackground(new java.awt.Color(238, 238, 238));
        myProfileButtonText.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        myProfileButtonText.setForeground(new java.awt.Color(222, 222, 222));
        myProfileButtonText.setText("Mój profil");
        myProfileButton.add(myProfileButtonText, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        myProfileButtonIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user_26_26.png"))); // NOI18N
        myProfileButton.add(myProfileButtonIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 18, -1, -1));

        myProfileButtonBar.setBackground(new java.awt.Color(0, 173, 181));
        myProfileButtonBar.setName("userBrick"); // NOI18N
        myProfileButtonBar.setOpaque(true);
        myProfileButton.add(myProfileButtonBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 20, 61, 20));

        menuPanel.add(myProfileButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 230, 60));

        mealDiaryButton.setBackground(new java.awt.Color(34, 40, 49));
        mealDiaryButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mealDiaryButton.setName(""); // NOI18N
        mealDiaryButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mealDiaryButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mealDiaryButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mealDiaryButtonMouseExited(evt);
            }
        });
        mealDiaryButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mealDiaryButtonText.setBackground(new java.awt.Color(0, 173, 181));
        mealDiaryButtonText.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        mealDiaryButtonText.setForeground(new java.awt.Color(222, 222, 222));
        mealDiaryButtonText.setText("Dziennik posiłków");
        mealDiaryButton.add(mealDiaryButtonText, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        mealDiaryButtonIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/note_26_26.png"))); // NOI18N
        mealDiaryButton.add(mealDiaryButtonIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 18, -1, -1));

        mealDiaryButtonBar.setBackground(new java.awt.Color(0, 173, 181));
        mealDiaryButtonBar.setName("userBrick"); // NOI18N
        mealDiaryButton.add(mealDiaryButtonBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 20, 108, 20));

        menuPanel.add(mealDiaryButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 230, 60));

        workoutDiaryButton.setBackground(new java.awt.Color(34, 40, 49));
        workoutDiaryButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        workoutDiaryButton.setName(""); // NOI18N
        workoutDiaryButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                workoutDiaryButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                workoutDiaryButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                workoutDiaryButtonMouseExited(evt);
            }
        });
        workoutDiaryButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        workoutDiaryButtonText.setBackground(new java.awt.Color(238, 238, 238));
        workoutDiaryButtonText.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        workoutDiaryButtonText.setForeground(new java.awt.Color(222, 222, 222));
        workoutDiaryButtonText.setText("Dziennik ćwiczeń");
        workoutDiaryButton.add(workoutDiaryButtonText, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        workoutDiaryButtonIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lift_26_26.png"))); // NOI18N
        workoutDiaryButton.add(workoutDiaryButtonIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 18, -1, -1));

        workoutDiaryButtonBar.setBackground(new java.awt.Color(0, 173, 181));
        workoutDiaryButtonBar.setName("userBrick"); // NOI18N
        workoutDiaryButton.add(workoutDiaryButtonBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 20, 104, 20));

        menuPanel.add(workoutDiaryButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 230, 60));

        statsButton.setBackground(new java.awt.Color(34, 40, 49));
        statsButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        statsButton.setName(""); // NOI18N
        statsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                statsButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                statsButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                statsButtonMouseExited(evt);
            }
        });
        statsButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        statsButtonText.setBackground(new java.awt.Color(238, 238, 238));
        statsButtonText.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        statsButtonText.setForeground(new java.awt.Color(222, 222, 222));
        statsButtonText.setText("Statystyki");
        statsButton.add(statsButtonText, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        statsButtonIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stats_26_26.png"))); // NOI18N
        statsButton.add(statsButtonIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 18, -1, -1));

        statsButtonBar.setBackground(new java.awt.Color(0, 173, 181));
        statsButtonBar.setName("userBrick"); // NOI18N
        statsButton.add(statsButtonBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 20, 55, 20));

        menuPanel.add(statsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 230, 60));

        calcButton.setBackground(new java.awt.Color(34, 40, 49));
        calcButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        calcButton.setName(""); // NOI18N
        calcButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calcButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                calcButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                calcButtonMouseExited(evt);
            }
        });
        calcButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        calcButtonText.setBackground(new java.awt.Color(238, 238, 238));
        calcButtonText.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        calcButtonText.setForeground(new java.awt.Color(222, 222, 222));
        calcButtonText.setText("Kalkulatory");
        calcButton.add(calcButtonText, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        calcButtonIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calc_26_26.png"))); // NOI18N
        calcButton.add(calcButtonIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 18, -1, -1));

        calcButtonBar.setBackground(new java.awt.Color(0, 173, 181));
        calcButtonBar.setName("userBrick"); // NOI18N
        calcButton.add(calcButtonBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 20, 67, 20));

        menuPanel.add(calcButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 230, 60));

        infoButton.setBackground(new java.awt.Color(34, 40, 49));
        infoButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        infoButton.setName(""); // NOI18N
        infoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                infoButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                infoButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                infoButtonMouseExited(evt);
            }
        });
        infoButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        infoButtonText.setBackground(new java.awt.Color(238, 238, 238));
        infoButtonText.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        infoButtonText.setForeground(new java.awt.Color(222, 222, 222));
        infoButtonText.setText("Informacje");
        infoButton.add(infoButtonText, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        infoButtonIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/info_26_26.png"))); // NOI18N
        infoButton.add(infoButtonIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 18, -1, -1));

        infoButtonBar.setBackground(new java.awt.Color(0, 173, 181));
        infoButtonBar.setName("userBrick"); // NOI18N
        infoButton.add(infoButtonBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 20, 66, 20));

        menuPanel.add(infoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 230, 60));

        closeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/close_20_20.png"))); // NOI18N
        closeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeButtonMouseClicked(evt);
            }
        });
        menuPanel.add(closeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        minimizeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minimize_20_20_2.png"))); // NOI18N
        minimizeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimizeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeButtonMouseClicked(evt);
            }
        });
        menuPanel.add(minimizeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        mainPanel.add(menuPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 0, 230, 720));

        jDesktopPane1.setBackground(new java.awt.Color(246, 246, 246));
        jDesktopPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        myProfilePanel.setBackground(new java.awt.Color(57, 62, 70));
        myProfilePanel.setPreferredSize(new java.awt.Dimension(1050, 720));
        myProfilePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        myProfileBanner.setBackground(new java.awt.Color(34, 40, 49));
        myProfileBanner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myprofile_banner.png"))); // NOI18N
        myProfileBanner.setOpaque(true);
        myProfilePanel.add(myProfileBanner, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, -1));

        namePanel.setBackground(new java.awt.Color(50, 54, 61));
        namePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nameText.setBackground(new java.awt.Color(238, 238, 238));
        nameText.setFont(new java.awt.Font("Segoe UI Light", 0, 90)); // NOI18N
        nameText.setForeground(new java.awt.Color(238, 238, 238));
        nameText.setText("Bartosz");
        namePanel.add(nameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 10, 580, 90));

        profileNameText.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        profileNameText.setForeground(new java.awt.Color(138, 152, 173));
        profileNameText.setText("Profil:");
        namePanel.add(profileNameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 7, -1, -1));

        jLabel1.setBackground(new java.awt.Color(0, 173, 181));
        jLabel1.setOpaque(true);
        namePanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 115, 605, 5));

        myProfilePanel.add(namePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 165, 605, 120));

        kcalPanel.setBackground(new java.awt.Color(50, 54, 61));
        kcalPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        todayKcalText.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        todayKcalText.setForeground(new java.awt.Color(138, 152, 173));
        todayKcalText.setText("Dostarczone dziś kalorie:");
        kcalPanel.add(todayKcalText, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 7, -1, -1));

        kcalValueText.setFont(new java.awt.Font("Segoe UI Light", 0, 72)); // NOI18N
        kcalValueText.setForeground(new java.awt.Color(238, 238, 238));
        kcalValueText.setText("1452");
        kcalPanel.add(kcalValueText, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 18, 180, 70));

        kcalIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kcal_13_13.png"))); // NOI18N
        kcalPanel.add(kcalIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 8, -1, -1));

        myProfilePanel.add(kcalPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 300, 605, 100));

        userParamPanel.setBackground(new java.awt.Color(50, 54, 61));
        userParamPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bmiText.setBackground(new java.awt.Color(238, 238, 238));
        bmiText.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        bmiText.setForeground(new java.awt.Color(138, 152, 173));
        bmiText.setText("BMI:");
        userParamPanel.add(bmiText, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 5, -1, -1));

        bmiValueText.setBackground(new java.awt.Color(238, 238, 238));
        bmiValueText.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        bmiValueText.setForeground(new java.awt.Color(238, 238, 238));
        bmiValueText.setText("21,3");
        userParamPanel.add(bmiValueText, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 15, -1, 40));

        noteText.setBackground(new java.awt.Color(238, 238, 238));
        noteText.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        noteText.setForeground(new java.awt.Color(138, 152, 173));
        noteText.setText("Ocena:");
        userParamPanel.add(noteText, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 60, -1, -1));

        noteValueText.setBackground(new java.awt.Color(238, 238, 238));
        noteValueText.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        noteValueText.setForeground(new java.awt.Color(238, 238, 238));
        noteValueText.setText("PRAWIDŁOWA");
        userParamPanel.add(noteValueText, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 65, -1, 40));

        goalText.setBackground(new java.awt.Color(238, 238, 238));
        goalText.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        goalText.setForeground(new java.awt.Color(138, 152, 173));
        goalText.setText("Cel:");
        userParamPanel.add(goalText, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 105, -1, -1));

        goalValueText.setBackground(new java.awt.Color(238, 238, 238));
        goalValueText.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        goalValueText.setForeground(new java.awt.Color(238, 238, 238));
        goalValueText.setText("60,0 kg");
        userParamPanel.add(goalValueText, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 110, -1, 40));

        goalLeftText.setBackground(new java.awt.Color(238, 238, 238));
        goalLeftText.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        goalLeftText.setForeground(new java.awt.Color(138, 152, 173));
        goalLeftText.setText("Do celu pozostało:");
        userParamPanel.add(goalLeftText, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 150, -1, -1));

        goalLeftValueText.setBackground(new java.awt.Color(238, 238, 238));
        goalLeftValueText.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        goalLeftValueText.setForeground(new java.awt.Color(238, 238, 238));
        goalLeftValueText.setText("-3,0 kg");
        userParamPanel.add(goalLeftValueText, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 155, -1, 40));

        maleIcon.setBackground(new java.awt.Color(0, 173, 181));
        maleIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/male_32_32.png"))); // NOI18N
        userParamPanel.add(maleIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 195, 30, -1));

        weightValuePanel.setBackground(new java.awt.Color(0, 173, 181));
        weightValuePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        weightText.setBackground(new java.awt.Color(238, 238, 238));
        weightText.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        weightText.setForeground(new java.awt.Color(238, 238, 238));
        weightText.setText("Waga:");
        weightValuePanel.add(weightText, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 5, -1, -1));

        weightValueText.setFont(new java.awt.Font("Segoe UI Light", 0, 72)); // NOI18N
        weightValueText.setForeground(new java.awt.Color(238, 238, 238));
        weightValueText.setText("63,0");
        weightValuePanel.add(weightValueText, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 80));

        heightText.setBackground(new java.awt.Color(238, 238, 238));
        heightText.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        heightText.setForeground(new java.awt.Color(238, 238, 238));
        heightText.setText("Wzrost:");
        weightValuePanel.add(heightText, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 95, -1, -1));

        heightValueText.setFont(new java.awt.Font("Segoe UI Light", 0, 48)); // NOI18N
        heightValueText.setForeground(new java.awt.Color(238, 238, 238));
        heightValueText.setText("172");
        weightValuePanel.add(heightValueText, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 110, -1, 40));

        paramChangeButton.setBackground(new java.awt.Color(238, 238, 238));
        paramChangeButton.setFont(new java.awt.Font("Segoe UI Light", 0, 10)); // NOI18N
        paramChangeButton.setForeground(new java.awt.Color(0, 173, 181));
        paramChangeButton.setText("   Zmień");
        paramChangeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        paramChangeButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        paramChangeButton.setOpaque(true);
        weightValuePanel.add(paramChangeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 215, 45, 15));

        cmText.setBackground(new java.awt.Color(0, 173, 181));
        cmText.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        cmText.setForeground(new java.awt.Color(238, 238, 238));
        cmText.setText("cm");
        weightValuePanel.add(cmText, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 120, -1, 30));

        ageText.setBackground(new java.awt.Color(238, 238, 238));
        ageText.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        ageText.setForeground(new java.awt.Color(238, 238, 238));
        ageText.setText("Wiek:");
        weightValuePanel.add(ageText, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 165, -1, -1));

        ageValueText.setFont(new java.awt.Font("Segoe UI Light", 0, 48)); // NOI18N
        ageValueText.setForeground(new java.awt.Color(238, 238, 238));
        ageValueText.setText("20");
        weightValuePanel.add(ageValueText, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 180, -1, 40));

        kgText.setBackground(new java.awt.Color(0, 173, 181));
        kgText.setFont(new java.awt.Font("Segoe UI Light", 0, 48)); // NOI18N
        kgText.setForeground(new java.awt.Color(238, 238, 238));
        kgText.setText("kg");
        weightValuePanel.add(kgText, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 25, -1, 70));

        userParamPanel.add(weightValuePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 240));

        myProfilePanel.add(userParamPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 165, 400, 235));

        jDesktopPane1.add(myProfilePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        mealDiaryPanel.setBackground(new java.awt.Color(57, 62, 70));
        mealDiaryPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mealDiaryBanner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mealdiary_banner_1.png"))); // NOI18N
        mealDiaryPanel.add(mealDiaryBanner, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jDesktopPane1.add(mealDiaryPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 720));

        workoutDiaryPanel.setBackground(new java.awt.Color(57, 62, 70));
        workoutDiaryPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        workoutDiaryBanner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/workoutdiary_banner.png"))); // NOI18N
        workoutDiaryPanel.add(workoutDiaryBanner, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jDesktopPane1.add(workoutDiaryPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 720));

        statsPanel.setBackground(new java.awt.Color(57, 62, 70));
        statsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        statsBanner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stats_banner_1.png"))); // NOI18N
        statsPanel.add(statsBanner, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jDesktopPane1.add(statsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 720));

        calcPanel.setBackground(new java.awt.Color(57, 62, 70));
        calcPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        calcBanner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calc_banner.png"))); // NOI18N
        calcPanel.add(calcBanner, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jDesktopPane1.add(calcPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 720));

        infoPanel.setBackground(new java.awt.Color(57, 62, 70));
        infoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        infoBanner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/info_banner.png"))); // NOI18N
        infoPanel.add(infoBanner, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jDesktopPane1.add(infoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 720));

        mainPanel.add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void myProfileButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myProfileButtonMouseClicked
        
        bar(myProfileButtonBar);
        myProfilePanel.setVisible(true);
        mealDiaryPanel.setVisible(false);
        workoutDiaryPanel.setVisible(false);
        statsPanel.setVisible(false);
        calcPanel.setVisible(false);
        infoPanel.setVisible(false);
        
    }//GEN-LAST:event_myProfileButtonMouseClicked

    private void myProfileButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myProfileButtonMouseEntered
        
        myProfileButton.setBackground(Color.decode("#20242c"));
        
    }//GEN-LAST:event_myProfileButtonMouseEntered

    private void myProfileButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myProfileButtonMouseExited
        
        myProfileButton.setBackground(Color.decode("#222831"));
        
    }//GEN-LAST:event_myProfileButtonMouseExited

    private void closeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButtonMouseClicked
        
        System.exit(0);

    }//GEN-LAST:event_closeButtonMouseClicked

    private void mealDiaryButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mealDiaryButtonMouseClicked
       
        bar(mealDiaryButtonBar);
        mealDiaryPanel.setVisible(true);
        myProfilePanel.setVisible(false);
        workoutDiaryPanel.setVisible(false);
        statsPanel.setVisible(false);
        calcPanel.setVisible(false);
        infoPanel.setVisible(false);
        
    }//GEN-LAST:event_mealDiaryButtonMouseClicked

    private void mealDiaryButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mealDiaryButtonMouseEntered
        
        mealDiaryButton.setBackground(Color.decode("#20242c"));
        
    }//GEN-LAST:event_mealDiaryButtonMouseEntered

    private void mealDiaryButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mealDiaryButtonMouseExited
        
        mealDiaryButton.setBackground(Color.decode("#222831"));
        
    }//GEN-LAST:event_mealDiaryButtonMouseExited

    private void workoutDiaryButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_workoutDiaryButtonMouseClicked
        
        bar(workoutDiaryButtonBar);
        workoutDiaryPanel.setVisible(true);
        myProfilePanel.setVisible(false);
        mealDiaryPanel.setVisible(false);
        statsPanel.setVisible(false);
        calcPanel.setVisible(false);
        infoPanel.setVisible(false);
        
    }//GEN-LAST:event_workoutDiaryButtonMouseClicked

    private void workoutDiaryButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_workoutDiaryButtonMouseEntered
        
        workoutDiaryButton.setBackground(Color.decode("#20242c"));
        
    }//GEN-LAST:event_workoutDiaryButtonMouseEntered

    private void workoutDiaryButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_workoutDiaryButtonMouseExited
        
        workoutDiaryButton.setBackground(Color.decode("#222831"));
        
    }//GEN-LAST:event_workoutDiaryButtonMouseExited

    private void statsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statsButtonMouseClicked
        
        bar(statsButtonBar);
        statsPanel.setVisible(true);
        myProfilePanel.setVisible(false);
        mealDiaryPanel.setVisible(false);
        workoutDiaryPanel.setVisible(false);
        calcPanel.setVisible(false);
        infoPanel.setVisible(false);
        
    }//GEN-LAST:event_statsButtonMouseClicked

    private void statsButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statsButtonMouseEntered
        
        statsButton.setBackground(Color.decode("#20242c"));
        
    }//GEN-LAST:event_statsButtonMouseEntered

    private void statsButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statsButtonMouseExited
        
        statsButton.setBackground(Color.decode("#222831"));
        
    }//GEN-LAST:event_statsButtonMouseExited

    private void calcButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calcButtonMouseClicked
        
        bar(calcButtonBar);
        calcPanel.setVisible(true);
        myProfilePanel.setVisible(false);
        mealDiaryPanel.setVisible(false);
        workoutDiaryPanel.setVisible(false);
        statsPanel.setVisible(false);
        infoPanel.setVisible(false);
                
    }//GEN-LAST:event_calcButtonMouseClicked

    private void calcButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calcButtonMouseEntered
        
        calcButton.setBackground(Color.decode("#20242c"));
        
    }//GEN-LAST:event_calcButtonMouseEntered

    private void calcButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calcButtonMouseExited
        
        calcButton.setBackground(Color.decode("#222831"));
        
    }//GEN-LAST:event_calcButtonMouseExited

    private void infoButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoButtonMouseClicked
        
        bar(infoButtonBar);
        infoPanel.setVisible(true);
        myProfilePanel.setVisible(false);
        mealDiaryPanel.setVisible(false);
        workoutDiaryPanel.setVisible(false);
        statsPanel.setVisible(false);
        calcPanel.setVisible(false);
        
    }//GEN-LAST:event_infoButtonMouseClicked

    private void infoButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoButtonMouseEntered
        
        infoButton.setBackground(Color.decode("#20242c"));
        
    }//GEN-LAST:event_infoButtonMouseEntered

    private void infoButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoButtonMouseExited
        
        infoButton.setBackground(Color.decode("#222831"));
        
    }//GEN-LAST:event_infoButtonMouseExited

    private void minimizeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeButtonMouseClicked
        
        setExtendedState(Frame.ICONIFIED);
        
    }//GEN-LAST:event_minimizeButtonMouseClicked
    
    
        
    public void bar(JLabel lab1) {
        
        myProfileButtonBar.setOpaque(false);
        mealDiaryButtonBar.setOpaque(false);
        workoutDiaryButtonBar.setOpaque(false);
        statsButtonBar.setOpaque(false);
        calcButtonBar.setOpaque(false);
        infoButtonBar.setOpaque(false);
        
        lab1.setOpaque(true);
        
        myProfileButtonBar.repaint();
        mealDiaryButtonBar.repaint();
        workoutDiaryButtonBar.repaint();
        statsButtonBar.repaint();
        calcButtonBar.repaint();
        infoButtonBar.repaint();
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            
            new GUI().setVisible(true);
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ageText;
    private javax.swing.JLabel ageValueText;
    private javax.swing.JLabel bmiText;
    private javax.swing.JLabel bmiValueText;
    private javax.swing.JLabel calcBanner;
    private javax.swing.JPanel calcButton;
    private javax.swing.JLabel calcButtonBar;
    private javax.swing.JLabel calcButtonIcon;
    private javax.swing.JLabel calcButtonText;
    private javax.swing.JPanel calcPanel;
    private javax.swing.JLabel closeButton;
    private javax.swing.JLabel cmText;
    private javax.swing.JLabel goalLeftText;
    private javax.swing.JLabel goalLeftValueText;
    private javax.swing.JLabel goalText;
    private javax.swing.JLabel goalValueText;
    private javax.swing.JLabel heightText;
    private javax.swing.JLabel heightValueText;
    private javax.swing.JLabel infoBanner;
    private javax.swing.JPanel infoButton;
    private javax.swing.JLabel infoButtonBar;
    private javax.swing.JLabel infoButtonIcon;
    private javax.swing.JLabel infoButtonText;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel kcalIcon;
    private javax.swing.JPanel kcalPanel;
    private javax.swing.JLabel kcalValueText;
    private javax.swing.JLabel kgText;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel maleIcon;
    private javax.swing.JLabel mealDiaryBanner;
    private javax.swing.JPanel mealDiaryButton;
    private javax.swing.JLabel mealDiaryButtonBar;
    private javax.swing.JLabel mealDiaryButtonIcon;
    private javax.swing.JLabel mealDiaryButtonText;
    private javax.swing.JPanel mealDiaryPanel;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JLabel minimizeButton;
    private javax.swing.JLabel myProfileBanner;
    private javax.swing.JPanel myProfileButton;
    private javax.swing.JLabel myProfileButtonBar;
    private javax.swing.JLabel myProfileButtonIcon;
    private javax.swing.JLabel myProfileButtonText;
    private javax.swing.JPanel myProfilePanel;
    private javax.swing.JPanel namePanel;
    private javax.swing.JLabel nameText;
    private javax.swing.JLabel noteText;
    private javax.swing.JLabel noteValueText;
    private javax.swing.JLabel paramChangeButton;
    private javax.swing.JLabel profileNameText;
    private javax.swing.JLabel statsBanner;
    private javax.swing.JPanel statsButton;
    private javax.swing.JLabel statsButtonBar;
    private javax.swing.JLabel statsButtonIcon;
    private javax.swing.JLabel statsButtonText;
    private javax.swing.JPanel statsPanel;
    private javax.swing.JLabel todayKcalText;
    private javax.swing.JPanel userParamPanel;
    private javax.swing.JLabel weightText;
    private javax.swing.JPanel weightValuePanel;
    private javax.swing.JLabel weightValueText;
    private javax.swing.JLabel workoutDiaryBanner;
    private javax.swing.JPanel workoutDiaryButton;
    private javax.swing.JLabel workoutDiaryButtonBar;
    private javax.swing.JLabel workoutDiaryButtonIcon;
    private javax.swing.JLabel workoutDiaryButtonText;
    private javax.swing.JPanel workoutDiaryPanel;
    // End of variables declaration//GEN-END:variables
}
